output "ip_addresses" {
    value = local_file.ip_addresses.id
    description = "Record the value of 'ip_addresses' ID, generated by 'ip_addresses' resource"
}

output "personal_info" {
    value = local_file.personal_info.id
    description = "Record the value of 'personal_info' ID, generated by 'personal_info' resource"
}

output "unique_ids" {
    value = local_file.unique_ids.id
    description = "Record the value of 'unique_ids' ID, generated by 'unique_ids' resource"
}