output "list_ip_addresses" {
    value = local_file.list_ip_addresses.id
    description = "Record the value of 'list_ip_addresses' ID,\ngenerated by 'list_ip_addresses' resource"
}

output "personal_info" {
    value = local_file.surname_name.id
    description = "Record the value of 'personal_info' ID,\ngenerated by 'surname_name' resource"
} 

output "unique_ids" {
    value = local_file.unique_ids.id
    description = "Record the value of 'unique_ids' ID,\ngenerated by 'unique_ids' resource"
}